name: Send Image to GAS

on:
  push:
    paths:
      - 'images/**'  # imagesフォルダに画像を追加してプッシュした時だけ動く

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Send to GAS
        run: |
          # 画像をBase64に変換して変数に格納
          BASE64_IMAGE=$(base64 -w 0 images/card.jpg)
          
          # GASへPOST送信
          curl -L -X POST "https://script.google.com/macros/s/AKfycbyahzhji_-4cQeFxaRvXwI1TaKLaAMLu-atNeEshuG-hvbZrNhgWIejccA9v1K-xOV4/exec?mode=github" \
            -H "Content-Type: application/json" \
            --data "{\"fileName\": \"card.jpg\", \"image\": \"data:image/jpeg;base64,$BASE64_IMAGE\"}"
