name: GCS Auth Test
on: [push]

jobs:
  test-auth:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

     - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/308432369710/locations/global/workloadIdentityPools/github-pool/providers/github'
          service_account: 'githubmeishikanri@github-actions-bot.iam.gserviceaccount.com'
          # ここにこの記述が必ず必要です！
          audience: 'google.github.actions'

      - name: 'Verify Authentication'
        run: gcloud auth list
