name: Upload to GCS
on:
  push:
    branches: [ "main" ]

jobs:
  upload:              # ここがジョブ名
    runs-on: ubuntu-latest  # ★ここがインデントされて、uploadの直下にある必要があります
    permissions:
      contents: 'read'
      id-token: 'write' 
    steps:
      - uses: actions/checkout@v4
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/308432369710/locations/global/workloadIdentityPools/github-pool/providers/github'
          service_account: 'githubmeishikanri@github-actions-bot.iam.gserviceaccount.com'
          audience: 'google.github.actions'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Upload image to GCS'
        run: |
          gcloud storage cp ./images/* gs://sakayabic-meishikanri-strage/
