name: Upload to GCS
on:
  repository_dispatch:
    types: [upload_meishi] # Cloud Run側の 'upload_meishi' に合わせました

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/308432369710/locations/global/workloadIdentityPools/github-pool/providers/github'
          service_account: 'githubmeishikanri@github-actions-bot.iam.gserviceaccount.com'
          audience: 'google.github.actions'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Create image file from payload'
        run: |
          mkdir -p images
          echo "${{ github.event.client_payload.base64Data }}" | base64 -d > ./images/${{ github.event.client_payload.fileName }}

      - name: 'Upload image to GCS'
        run: |
          gcloud storage cp ./images/${{ github.event.client_payload.fileName }} gs://sakayabic-meishikanri-strage/
